# Generated by Django 4.1.2 on 2022-10-07 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('CurrentBalance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=255)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('DateCreate', models.DateTimeField(auto_now_add=True)),
                ('BankAccountId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='BankAccountId', to='bankingapi.bankaccount')),
                ('RelateBankAccountId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='RelateBankAccountId', to='bankingapi.bankaccount')),
            ],
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='CustomerId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bankingapi.customer'),
        ),
    ]
